{% raw -%}
- hosts: all
  tasks:
    - name: log deployment
      lineinfile:
        create: true
        dest: /services/deploy.log
        line: ===== {{ inventory_dir|basename }} letsencrypt @ {{ now() }} =====
    - name: deploy hook
      copy:
        dest: /services/nginx/etc/renewal-hooks/deploy/run
        mode: 0777
        content: |
          #!/bin/bash
          set -euxo pipefail
          cp $RENEWED_LINEAGE/*.pem /shared/$RENEWED_DOMAINS/etc/
          ps fauxww
          kill -HUP 1
    - name: fix cron PATH
      cron:
        env: true
        name: PATH
        job: '{{ ansible_env.PATH }}'
    - name: install renewal cron job
      cron:
        name: certbot_renew
        minute: '0'
        hour: '1'
        job: docker compose exec --no-TTY nginx certbot renew >> /services/nginx/logs/cron.log 2>&1
    - name: initial setup
      shell:
        executable: /bin/bash
        cmd: |
          exec > >(tee -a /services/deploy.log) 2>&1
          set -euxo pipefail
          docker compose run --rm --no-TTY nginx certbot certonly \
            --webroot \
            --agree-tos \
            --preferred-challenges=http-01 \
            --email={{ admin_email }} \
            --webroot-path=/shared/{{ server_name }} \
            --domain={{ server_name }} \
            --non-interactive \
            --keep-until-expiring 2>&1 | tee -a /services/nginx/logs/setup.log
    - name: manually copy certs
      shell:
        executable: /bin/bash
        cmd: |
          exec > >(tee -a /services/deploy.log) 2>&1
          set -euxo pipefail
          docker compose run --rm --no-TTY \
            -e 'RENEWED_LINEAGE=/etc/letsencrypt/live/{{ server_name }}' \
            -e 'RENEWED_DOMAINS={{ server_name }}' \
            nginx /etc/letsencrypt/renewal-hooks/deploy/run >> /services/nginx/logs/setup.log
    - name: reload nginx
      shell:
        executable: /bin/bash
        cmd: |
          exec > >(tee -a /services/deploy.log) 2>&1
          set -euxo pipefail
          docker compose kill --signal HUP nginx
{% endraw -%}
